# Set the default stages where the hooks will run
default_stages: [commit]

repos:
# -----------------------------------------------------------------------------
# 1. Standard hooks for general file hygiene
# -----------------------------------------------------------------------------
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace         # Trims trailing whitespace
    -   id: end-of-file-fixer           # Ensures files end with a single newline
    -   id: check-yaml                  # Checks YAML files for parseable syntax
    -   id: check-toml                  # Checks TOML files for parseable syntax
    -   id: check-added-large-files     # Prevents committing large files > 1MB
        args: ['--maxkb=1000']

# -----------------------------------------------------------------------------
# 2. Ruff for lightning-fast Python linting and formatting
# -----------------------------------------------------------------------------
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest ruff version at https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
    # Run the linter and auto-fix what's safe
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter
    -   id: ruff-format

# -----------------------------------------------------------------------------
# 3. Notebook cleaner to strip output before committing
# -----------------------------------------------------------------------------
-   repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    -   id: nbstripout
        # This strips all output cells from Jupyter notebooks,
        # keeping your git history clean.
